const Map<String, String> english = {
  ...app_english,
  ...wallet_english,
};

const Map<String, String> app_english = {
  "productsSearch": "Search In Products",
  "newsAndBLogs": "Blogs And News",
  "personalInfo": "My Personal Info",
  "changePassword": "Change Password",
  "enter_app": "Enter App",
  "full_name": "Full Name",
  "repeat_password": "Repeat Password",
  "confirm_text_number": "Confirm Text Number",
  "register_app": "Register App",
  "enter": "Enter",
  "currentPassword": "Current Password",
  "forgot_pass": "Forgot Password",
  "phone_number": "Phone Number",
  "confirm_text": "Enter the code sent to your number",
  "set_new_password": "Set New Password",
  "import_new_password": "Import New Password",
  "recent_news": "Recent News",
  "addToCard": "Add To Shopping Card",
  "addToCardSuccesful": ""
      "Succesfully Added To Card",
  "sign_in": "Sign In",
  "forgot_pass_t": "Forgot Your Password",
  "newPassword": "New Password",
  "confirm_code": "Confirm Code",
  "repeatNewPassword": "Repeat New Password",
  "myOrder": "My Orders",
  'insertSearch': "Please search for the desired phrase",
  "similarProduct": "Similar Products",
  "newsDetail": "News Details",
  "similarNews": 'Similar News',
  "language_but": "Continue in English",
  "productDetails": "Product Details",
  "enterPhone": "Enter your Cellphone number",
  "confirmAndContinue": "Confirm and continue",
  "enterVerifyCode": "Enter confirmation code",
  "resendCode": "Resend again",
  "editPhone": "Edit cellphone number",
  "callSupport": "Call support",
  "setPassword": "Create password",
  "createNewPassword": "Create new password",
  "passWordShouldBe4": "The code should be 4 digits",
  "completeInformation": "Complete information",
  "firstName": "Name",
  "lastName": "Lastname",
  'name': 'Name',
  'saveInfo': 'ُSave Information',
  "birthday": "Birthday",
  "search_flights": "Search flights",
  "day": "Day",
  "month": "Month",
  "year": "Year",
  "province": "State",
  "gender": "Gender",
  "male": "Male",
  "female": "Female",
  "fillLater": "Fill it later",
  "coin": "Coin",
  "increaseBalance": "Add balance",
  "ourServices": "Our  Services",
  "chargePhone": "Top-up Mobile",
  "internet": "Internet",
  "walletToWallet": "Send Coin",
  "payBills": "Pay Bills",
  "innerHotel": "Domestic Hotel",
  "foreignHotel": "Foreign Hotel",
  "foreignHotelsList": "Foreign Hotels List",
  "innerFlights": "Domestic Flight",
  "foreignFlights": "Foreign Flight",
  "comingSoon": "Coming soon",
  "home": "Home",
  "barcode": "QR",
  "coinBag": "Coin Wallet",
  "searchForeignHotel": "Search hotels",
  "addRoom": "Add room",
  "search": "Search",
  "searchSummary": "Search summery",
  "searchAgain": "Search again",
  "searchWithHotelName": "Search hotel name",
  "showOnMap": "Show on map",
  "sort": "Sort",
  "submit": "Submit",
  "removeFilters": "Remove Filters",
  "highestPrice": "Highest price",
  "hotelName": "Hotel name",
  "chooseRoom": "Choose room",
  "filtering": "Filter",
  "startPrice": "Starting price",
  "sortAndFiltering": "Sort and filter",
  "accordingToGrade": "Based on grade",
  "facilities": "Facilities",
  "meal": "Meal",
  "priceRange": "Price range",
  "region": "Region",
  "clearFilters": "Clear filter",
  "hotelPage": "Hotel page",
  "hotelInformation": "Hotel information",
  "hotelContact": "Hotel contact",
  "hotelFacilities": "Hotel facilities",
  "roomFacilities": "Room facilities",
  "hotelDetail": "Hotel details",
  "directCall": "Direct calling",
  "more": "More",
  "reserveRoom": "Book room",
  "passengersInformation": "Passengers info",
  "enterPassengersDetails": "Enter Passengers Details",
  "passengersInfoInput": "Enter passenger information",
  "pay": "Pay",
  "make_payment": "Make Payment",
  "bookerContactInfo": "Booker Contact Info",
  "bookerContactInfoDesc": "Booking details and tickets will be send to this email or phone number",
  "reservatoreCallInfo": "Booking information ",
  "email": "Email",
  "optional": "- Optional -",
  "phoneNumber": "Cellphone number",
  "passengersDetail": "Passengers details",
  "passengerDetail": "Passenger Details",
  "passengerDetailDesc": "Please enter your first and lastname correctly in English format.",
  "nationality": "Nationality",
  "addPassenger": "Add passenger",
  "removePassenger": "Remove passenger",
  "putDescriptionHere": "Enter description",
  "considerations": "Note",
  "searchIranianFlight": "Search domestic flight",
  "beginning": "Origin",
  "destination": "Destination",
  "dateOfDeparture": "Flight date",
  "departing": "Departing",
  "location": "Location",
  "returning": "Returning",
  "count": "Passenger",
  "research": "Research",
  "selectRoom": "Select Room",
  "classs": "Class",
  "innerFlightList": "Domestic flight list",
  "flights_ticket": "Flights Ticket",
  "flights_list": "Flights List",
  "select": "Select",
  "change": "Change",
  "buy_pay_now": "Buy & Pay Now",
  "canceling_rules": "Canceling Rules & Price Table",
  "choose": "Choose",
  "remaining": "Remaining",
  "person": "Person",
  "lowestPrice": "Lowest price",
  "highestDiscount": "Highest discount",
  "moreDetail": "More info",
  "innerFlightTicket": "Domestic flight ticket",
  "flightLength": "Flight duration",
  "priceDetail": "Price details",
  "adult": "Adult",
  "child": "Child",
  "baby": "Infants",
  "refundRule": "Refund policy",
  "understand": "Undrestood",
  "iranian": "Iranian",
  "foreign": "Foreigner",
  "englishName": "Name in English",
  "englishLastName": "Surname in English",
  "example": "Example",
  "enterYourNameCorrectly": "Enter your name",
  "andSameAsPassport": "in passport",
  "georgian": "Georgian",
  "iDNumber": "ID Number",
  "countryOfBirth": "Place of birth",
  "countryOfIssue": "Place of issue",
  "passportExpirationDate": "Passport expiry date",
  "oneWayFlight": "One-way",
  "twoWayFlight": "Round-trip",
  "options": "Options",
  "pricing": "Pricing",
  "byRating": "By Rating",
  "roundtrip": "Roundtrip",
  "leavingFrom": "Leaving from",
  "goingTo": "Going to",
  "traveler_count": "Traveler Count",
  "flight_class": "Flight Class",
  "returningDate": "Return",
  "edit": "Edit",
  "stop": "Stop",
  "flightRulesAndCancelation": "Flight and cancellation rules",
  "basicPrice": "Base price",
  "tax": "Tax",
  "totalPrice": "Total price",
  "reserve": "Reservation",
  "flightNumber": "Flight number",
  "allowedCargo": "Allowed cargo",
  "passportNumber": "Passport number",
  "myPhoneNumber": "My phone number",
  "enterPhoneNumber": "Enter your phone number",
  "fromContacts": "From contacts",
  "operatorWillBeRecognized": "Operator will be recognized automatically",
  "buyCharge": "Add top-up",
  "chooseSimCart": "Choose simcard",
  "credit": "Credit",
  "permanent": "Postpaid",
  "rial": "Rial",
  "chosenPrice": "Selected price",
  "from": "from",
  "chooseIntendedCharge": "Select top-up amount",
  "equal": "Equal",
  "walletBagBalance": "Wallet Balance",
  "insufficientBalance": "Insufficent balance",
  "watterBill": "Water bill",
  "powerBill": "Electricity Bill",
  "gasBill": "Gas Bill",
  "phoneBill": "Telephone Bill",
  "mobileBill": "Cellphone Bill",
  "violation": "Fines",
  "otherBills": "Other Bills",
  "readGuid": "Guide",
  "view": "View",
  "paperBill": "Paper Bill",
  "id": "ID",
  "billsHistory": "Bills history",
  "billInquiry": "Bill inquiry",
  "barcodeScan": "Scan barcode",
  "bill": "Bill",
  "price": "Price",
  "cityCode": "City code",
  "staticPhoneNumber": "Landline phone number",
  "staticPhone": "Landline phone",
  "chooseOperator": "Select operator",
  "guid": "Guide",
  "inCaseOfTransfer": "In case of tranfer",
  "watter": "Water",
  "power": "Electricity",
  "gas": "Gas",
  "mobile": "Cellphone",
  "chooseTimeRange": "Time range",
  "paymentId": "Payment ID",
  "billId": "Bill ID",
  "toman": "Toman",
  "lastPayments": "Last payments",
  "billType": "Bill type",
  "trackingNumber": "Tracking number",
  "successFull": "Successful",
  "paymentSuccessful": "Payment successful",
  "hourly": "Hourly",
  "daily": "Daily",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "threeWeeks": "3 months",
  "sixWeeks": "6 months",
  "yearly": "Yearly",
  "gig": "Gigabyte",
  "internetPackage": "Internet package",
  "nextLevel": "Next",
  "myProfile": "My profile",
  "qAnda": "Q&A",
  "support": "Support",
  "rulesAndConditions": "Terms and conditions",
  "shareWithFriends": "Share with friends",
  "aboutUs": "About us",
  "exitApp": "Exit",
  "ourSocialMedias": "Our social medias",
  "copy": "Copy",
  "yourBalance": "Your balance",
  "sendNewTicket": "Send new ticket",
  "ticketTitle": "Title",
  "ticketText": "Description",
  "writeHere": "Write here",
  "writeYourProblemHere": "Write your problem here",
  "addAttachment": "Add attachment",
  "chooseFile": "Select file",
  "addToDraft": "Add to draft",
  "chooseFlight": "Choose Flight",
  "nationalCode": "National Code",
  "billServices": "Bill Services",
  "enterBillIdAndPayId": "Enter Bill Id And PayId",
  "chooseInternetPackage": "Choose Internet Package",
  "pleaseChooseInternetPackage": "Please Choose Internet Package",
  "ticketList": "Tickets List",
  "youCanSeeListTicket": "You can see list of tickets",
};

const Map<String, String> wallet_english = {
  'app_name': 'LiquWallet',
  'about_app': 'LiquWallet intends to conquer all peaks such as Bitcoin, Ethereum, Solana, BSC, Talan, Tron, DOT, Cardano. etc.'
      ' What LiquWallet is going to do is to make it possible for users to swap and exchange native coins and tokens of all these protocols.'
      ' The main point about LiquWallet is that as there is enough technical knowledge to make it possible to add up any other blockchain,'
      ' LiquWallet is somehow limitless! But moreover, the attractive capability which is to be offered in second phase of the project is P2P trading possibility.'
      ' This characteristic will be possible as there is no KYC process needed.',
  'lock_screen_description': 'The password must be a 6 digit number',
  'ok': 'Ok',
  'talan': 'Talan',
  'dart_lorem_epsom': 'Dart programming language,'
      ' containing reusable libraries & packages for Flutter,'
      ' AngularDart, and general Dart programs',
  'cryptocurrency': 'Cryptocurrency',
  'get_started': 'Get Started',
  'pin_codes_not_match': "Pin codes doesn't match , try again",
  'generate_seed_description_message': 'Please copy and keep it in a safe place.'
      ' The seed words is the only way to restore '
      'your wallet.once lost,it cannot be retrieved .'
      ' Do not use screenshots,photos,etc.to save',
  'generate_seed_message_understand': 'I understand that if I lose my seed words , no one can help me recover. '
      'I will never be able to retrieve the assets in my wallet',
  'verify_seeds_desc_message': 'Please click on the candidate word in order accourding to the'
      ' seed words you backed up to verify thet the backup seed words is accurate.',
  'about': 'About',
  'about_talan_wallet': 'Talan wallet is a digital asset mobile wallet that supports TALAN and TLRC20 tokens.'
      ' The mobile wallet provids secure storage of Talan network native coin and tokens and digital asset transaction services.',
  'terms_of_service': 'Terms of Service',
  'balance_token_name': 'Balance (@tokenName)',
  'contract_address': 'Contract Address : ',
  'send': 'Send',
  'receive': 'Receive',
  'transactions': 'Transactions',
  'nothing_found': 'Nothing Found',
  'try_again': 'Try Again',
  'all': 'All',
  'backup_seed_words': 'Backup seed words',
  'warning': 'Warning!',
  'read_agreement_first': 'Please read and agree to the agreement first.',
  'regenerate': 'Regenerate',
  'backed_up': 'Backed Up',
  'tokens': 'Tokens',
  'balance_talan': 'Balance (Talan)',
  'pending_balance': 'Pending : @pending Talan',
  'first_slide_description': 'Receive TALAN and TLRC20 tokens by scanning or sharing your unique QR code or address',
  'second_slide_description': 'Send TALAN or TLRC20 tokens in a few taps by scanning a QR code or pasting an address',
  'control_your_wealth': 'Control Yor Wealth',
  'third_slide_description': 'Funds are under control and your privacy is protected,'
      ' no account required and your private key is stored on no server',
  'create_new_wallet': 'Create New Wallet',
  'restore_wallet': 'Restore Wallet',
  'copy_address': 'Copy Address',
  'addPassengers': 'Add Passengers',
  'amount': 'Amount',
  'enter_amount': 'Enter amount',
  'restore_wallet_description': 'Please enter your wallet seed words to restore it',
  'confirm': 'Confirm',
  'security_center': 'Security Center',
  'your_address': 'Your Address',
  'public_key': 'Public Key',
  'private_key': 'Private Key',
  'tap_to_reveal': 'Tap to reveal',
  'next': 'Next',
  'available_balance': 'Available balance',
  'to': 'TO',
  'enter_your_address': 'Please enter address or',
  'paste': 'paste',
  'address': 'Address',
  'settings': 'Settings',
  'language': 'Language',
  'currency_unit': 'Currency unit',
  'touch_id': 'Touch ID',
  'modify_pi_code': 'Modify Pin Code',
  'delete_your_wallet': 'Delete your wallet',
  'confirm_backup': 'Confirm Backup',
  'wallet_created': 'Wallet Created',
  'secure_your_key': 'Please keep your security key and password in safe place.',
  'access_your_wallet': 'Access your wallet',
  'previous': 'Previous',
  'confirm_transaction': 'Confirm Transaction',
  'you_are_about_to_send': 'You are about to send ',
  'space_to': ' to',
  'are_you_sure_to_send': 'Are you sure to send ?',
  'delete_wallet': 'Delete Wallet',
  'delete_wallet_description': 'You are about to delete your wallet.'
      ' Be sure you have got your seed words/private key written down,'
      ' Otherwise you will lose all your Tokens and cannot recover them.'
      ' Are you sure you want to delete your wallet? ',
  'yes_iam_sure': 'Yes I\'m sure',
  'cancel': 'Cancel',
  'transaction_sent': 'Transaction sent successfully',
  'transaction_sent_description': 'Transaction sent successfully. The following text is transaction ID',
  'copied_to_clipboard': 'Copied into your clipboard',
  'pin_codes_do_not_match': 'Pin codes don\'t match. Try again',
  'enter_your_current_pin_code': 'Enter your current pin code',
  'enter_new_pin_code': 'Enter new pin code',
  'please_enter_password': 'Please enter password',
  'enter_pin_code_to_unlock_app': 'Enter the pin code to unlock the app',
  'incorrect_pin_code': 'Incorrect Pin Code\nRetry Again',
  'incorrect_pin_code_toast': 'Incorrect pin code. Try again',
  'enter_pin_code': 'Please enter pin code',
  'reenter_for_confirmation': 'Re-enter for confirmation',
  'auth_failed': 'Authentication Failed',
  'address_copied': 'Address copied to your clipboard',
  'your_wallet_deleted': 'Your wallet has been deleted',
  'incorrect_order': 'You have not entered words in correct order',
  'internet_not_connected': 'You\'re not connected to internet',
  'agree_to_terms_of_service': 'You need to agree with our terms of services before continuing',
  'sync_first': 'You need to sync first',
  'last_sync_date_time': 'You\'re not connected to network, last sync was on'
      '@date'
      ' at @time',
  'fill_all_fields': 'You must fill all fields',
  'invalid_seed': 'Invalid seed phrase',
  'more_balance_needed': 'You don\'t have this much balance to send',
  'invalid_inputs': 'Invalid inputs',
  'something_went_wrong': 'Something went wrong!',
  'yes': 'Yes',
  'en': 'English',
  'fa': 'فارسی',
  'wallet': 'Wallet',
  'services': 'Services',
  'dex': 'EXCH',
  'offline_stacking': 'Offline Staking',
  'add_delegation': 'Add Delegation',
  'super_staker_address': 'Super Staker Address',
  'staker_fee': 'Staker Fee',
  'enter_fee': 'Enter Fee',
  'attention': 'Attention',
  'staking_confirmation_message': 'Are you sure to to put your coins for staking?',
  'staking_done_message': 'Delegation for staking confirmed. Wait for 300 blocks to be confirmed in blockchain to start receiving staking rewards.',
  'done': 'Done!',
  'staking_block_number': 'Staking Block Number',
  'blocks_confirmed_so_far': 'Blocks Confirmed So Far',
  'cancel_staking': 'Cancel Staking',
  'remove_stake_confirmation_message': 'You are about to cancel staking. Are you sure about it?',
  'amount_balance_required': '@amount Talans is required',
  'nothing_to_show': 'Still nothing to show',
  'coming_soon': 'Coming Soon',
  'staker_address': 'Super Staker Address',
  'fee': 'Fee',
  'about_offline_staking': 'About Offline Staking',
  'offline_staking_description': 'Offline Staking allows holders to choose the operator of the node, while not transferring'
      'their coins to him. Receiving rewards gives users the opportunity to earn profits from staking their coins.'
      'In offline staking , you don\'t need to setup a full node and you even never let your coins to leave your wallet.'
      'Just you show the blockchain that you let the super staker use your address and for this reason you pay fee to super staker node.'
      'The duty of super staker is to be online all the time.'
      'Since Talan’s offline staking does not need an internet connection, it is called offline'
      'staking. In it, instead of tokens, the owners delegate their wallets addresses. The coins'
      'themselves remain in the owner’s wallet and can be used at any given time.The stakers'
      'are separated into two categories, as they are in all Blockchain networks: superstakers'
      'and UTXO representatives, known as Delegators. To participate in offline staking, the'
      'representative’s wallet address is sent to a superstaker.'
      'The superstakers then can act on behalf of the delegators and take a cut of the profits'
      'for doing the staking. However, after the delegation of the wallet,'
      'the owner doesn’t have to be online at all times which means that the owners will receive interest even if they'
      'are not participating directly. The time frames for receiving the rewards is directly'
      'related to the amount of delegated Talans. The more coins you have for staking, the'
      'sooner you will receive the block’s rewards.',
  'canceling_stake_wait_for_blockchain': 'Canceling stake. Wait for blockchain confirmation.',
  'seed_phrase': 'Seed Phrase',
  'restore_wallet_with_private_key_description': 'Please enter your wallet private key to restore it',
  'invalid_private_key': 'Invalid Private Key',
  'staked': 'Staked',
  'confirmations': 'Confirmations',
  'address_equality': 'Super staker address can not be equal to your own address',
  'super_staker_not_verified': 'The provided address is not recognized as a super staker address.',
  'private_key_reveal_warning': 'Under no circumstances share your Private Key with anyone. Otherwise,'
      ' the one with your Private Key information can access your wallet.',
  'failed_to_create_wallet': 'Failed to create wallet',
  'wallet_name': 'Wallet Name',
  'wallet_name_required': 'You need to enter wallet name',
  'restore': 'Restore',
  'multi_coin_wallet': 'Multi-Coin Wallet',
  'no_balance_to_send': 'You have no balance to send',
  'search_tokens_hint': 'Search tokens...',
  'wallets': 'Wallets',
  'wallet_settings': '@name settings',
  'edit_wallet_name': 'Edit Wallet Name',
  'export_private_key': 'Export Wallet Private Key',
  'export_wallet_seed_phrase': 'Export Wallet Seed Phrase',
  'save': 'Save',
  'empty_wallet_name_message': 'You need to enter a name for wallet',
  'new_name_saved': 'New wallet name saved',
  'export_seed_phrase_title': 'Export Wallet Seed Phrase',
  'export_private_key_title': 'Export Wallet Private Key',
  'copy_seed_phrase': 'Copy Seed Phrase',
  'copy_private_key': 'Copy Private Key',
  'copied': 'Copied',
  'export_seed_phrase_message': 'Qr-code above contains your seed phrase',
  'export_private_key_message': 'Qr-code above contains your private key',
  'exchange': 'Exchange',
  'swap': 'Swap',
  'you_pay': 'You Pay',
  'you_get': 'You Get',
  'balance': 'Balance : ',
  'unable_to_add_the_token': 'Unable to add the token to your wallet',
  'processing': 'Processing',
  'finished': 'Finished',
  'failed': 'Failed',
  'from_address': 'From Address :',
  'to_address': 'To Address :',
  'pay_in_txid': 'Pay In Transaction Id :',
  'pay_out_txid': 'Pay Out Transaction Id :',
  'date': 'Date',
  'network_fee': 'Network Fee : ',
  'enter_valid_amount': 'Enter valid amount to proceed',
  'minimum_amount_required': 'Minimum amount for @name is @amount',
  'maximum_amount_required': 'Maximum amount for @name is @amount',
  'proceed': 'Proceed',
  'amount_of_coin': 'Amount @name',
  'exchange_history': 'Exchange History',
  'swap_history': 'Swap History',
  'buy': 'Buy',
  'sell': 'Sell',
  'total': 'Total',
  'transfer_done': 'Transfer Done',
  'dex_transfer_message': 'Your order submitted and it will be processed soon. Code below is your order id',
  'only_this_pair': 'Only @token1 to @token2',
  'all_orders': 'All Orders',
  'search_token_you_pay': 'Search the token you want to pay',
  'search_token_you_get': 'Search the token you want to get',
  'not_enough_token': 'Not enough @token to make the exchange',
  'request_canceled': 'Request canceled',
  'maintenance_message': 'Unfortunately app is under maintenance right now, please try to open the wallet a few moment later',
  'unexpected_problem_try_later': 'Something unexpected happened, please try again later',
  'exchanging': 'Exchanging',
  'sending': 'Sending',
  'refunded': 'Refunded',
  'hold': 'Hold',
  'expired': 'Expired',
  'total_value': 'Total Value',
  'pay_in_confirmations': 'Pay in confirmations : ',
  'pay_out_confirmations': 'Pay out confirmations : ',
  'memo': 'Memo',
  'tag': 'Tag',
  'enter_memo': 'Enter Memo (Optional)',
  'enter_tag': 'Enter Tag (Optional)',
  'swap_unavailable': 'Currently swap is unavailable',
  'exchange_unavailable': 'Currently exchange is unavailable',
  'collections': 'Collections',
  'create_nft': 'Create NFT',
  'nft_name': 'NFT Name',
  'nft_desc': 'NFT Description',
  'nft_amount': 'NFT Amount (Max: 30)',
  'enter_name': 'Enter Name',
  'enter_desc': 'Enter Description',
  'nft_image_required': 'NFT image is required',
  'nft_name_required': 'NFT Name is required',
  'nft_amount_required': 'NFT amount is required',
  'nft_amount_could_not_be_zero': 'NFT amount could not be zero',
  'nft_amount_exceeded': 'NFT amount exceeded maximum amount allowed',
  'nft_desc_required': 'NFT description is required',
  'nft_created_message': 'Nft created successfully. The following text is its transaction ID',
  'nft_created_title': 'NFT Created',
  'unable_to_load': 'Unable to load',
  'transaction_id': 'Transaction ID',
  'description': 'Description',
  'available_amount': 'Available Amount',
  'your_balance': 'Your Balance',
  'date_created': 'Creation Date',
  'send_nft': 'Send NFT',
  'address_required': 'Address required',
  'not_enough_nft_amount': "You don't have enough NFT to send",
  'ipfs': 'IPFS',
  'create_nft_confirmation_message': 'Are you sure about creating this NFT',
  'nft_author': 'Author',
  'nft_author_hint': 'Enter Author Name (optional)',
  'author_address': 'Author\'s Address'
};
