const Map<String, String> persian = {
  ...persianApp,
  ...persianWallet,
};

const Map<String, String> persianWallet = {
  "productsSearch": "سرچ در محصولات",
  "newsAndBLogs": "اخبار و مطالب",
  "personalInfo": "اطلاعات شخصی من",
  "myOrder": "سفارشات من",
  "similarProduct": "محصولات مشابه",
  "newsDetail": "جزِئیات خبر",
  "similarNews": 'مطالب مشابه',
  "addToCard": "افزودن به سبد خرید",
  "addToCardSuccesful": ""
      "به سید خرید اضافه شد",
  "language_but": "ادامه به زبان فارسی",
  "productDetails": "جزییات محصول",
  'main': 'صفحه اصلی',
  'phone_number': 'شماره تماس خود را وارد کنید',
  'confirm_phone': 'تایید تلفن همراه',
  'password': 'کلمه ی عبور',
  "currentPassword": "کلمه ی عبور فعلی",
  "newPassword": "کلمه ی عبور جدید",
  "repeatNewPassword": "تکرار کلمه ی عبور جدید",
  'enter': 'ورود',
  'enter_app': 'ورود به ابلیکیشن',
  'enter_system': 'ورود به سیسنم',
  'register_app': 'ثبت نام در اپلیکیشن',
  'sign_in': 'حساب کاربری ندارید؟ ثبت نام',
  'sign': 'ثبت نام',
  'forgot_pass': 'فراموشی رمز عبور',
  'forgot_pass_t': 'رمز عبورم را فراموش کرده ام',
  'set_new_password': 'تنظیم مجدد کلمه ی عبور',
  'import_new_password': 'رمز عبور جدید خود را وارد نمایید',
  'repeat_password': 'تکرار رمز عبور جدید',
  'confirm_text': 'کد تایید را وارد نمایید',
  'confirm_text_number': 'کد ارسال شده به شماره خود را وارد نمایید',
  'confirm_code': 'تایید کد',
  'full_name': 'نام و نام خانوادگی',
  'name': 'نام',
  'saveInfo': 'ذخیره اطلاعات',
  'categories': 'دسته بندی ها',
  'girl_dress': "لباس دخترانه",
  'new_born': 'لباس نوزاد',
  "baby_shoes": "کفش کودک",
  "winter_close": "لباس زمستانی",
  "specials": "محصولات ویژه",
  'recent_news': "جدیدترین اخبار",
  'insertSearch': "لطفا عبارت مورد نظر را جستجو کنید",
  'about_app': 'Liquwallet intends to conquer all peaks such as Bitcoin, Ethereum, Solana, BSC, Talan, Tron, DOT, Cardano. etc.'
      ' What Liqu Wallet is going to do is to make it possible for honorable users to swap and exchange native coins and tokens of all these protocols.'
      ' The main point about Liqu Wallet is that as there is enough technical knowledge to make it possible to add up any other blockchain,'
      ' Liqu Wallet is somehow limitless! But moreover, the attractive capability which is to be offered in second phase of the project is P2P trading possibility.'
      ' This characteristic will be possible as there is no KYC process needed.',
  'lock_screen_description': 'رمز باید ۶ رقم داشته باشد',
  'ok': 'باشه',
  'talan': 'طلان',
  'dart_lorem_epsom': 'Dart programming language,'
      ' containing reusable libraries & packages for Flutter,'
      ' AngularDart, and general Dart programs',
  'cryptocurrency': 'رمز ارز',
  'get_started': 'شروع',
  'pin_codes_not_match': 'رمز ها با یکدیگر تطابق ندارند . دوباره سعی کنید',
  'generate_seed_description_message': 'لطفا از این رونوشت برداشته و آن را در جای امنی ذخیره کنید'
      ' عبارت های رمز تنها راه بازیابی کیف پول شما هستند . '
      'در صورتی گم شدن قابل برگشت نیستند . '
      ' برای ذخیره سازی از اسکرین شات یا عکس و یا موارد دیگر استفاده نکنید . ',
  'generate_seed_message_understand': 'متوجهم که در صورت از دست دادن عبارات رمز هیچ کس در بازیابی آن نمیتواند به من کمک کند . '
      'امکان بازیابی محتوای کیف پول برای من امکان پذیر نخواهد بود . ',
  'verify_seeds_desc_message': 'کلمات ارائه شده را براساس عبارت رمزی که پیش تر ذخیره کردید'
      'انتخاب کنید تا از دقیق بودن نسخه ی ذخیره شده ی شما اطمینان حاصل گردد . ',
  'about': 'درباره',
  'about_talan_wallet': 'کیف پول طلان ، یک کیف پول ارز دیجیتال قابل حمل می باشد که توکن های TALAN و TLRC20 را پشتیبانی میکند . '
      'نسخه ی موبایل این کیف پول محل ذخیره ی امنی برای سکه ی بومی شبکه ی طلان و خدمات ارسال تراکنش را ارائه می دهد',
  'terms_of_service': 'شرایط استفاده از خدمات',
  'balance_token_name': 'موجودی (@tokenName)',
  'contract_address': 'آدرس قرارداد : ',
  'send': 'ارسال',
  'receive': 'دریافت',
  'transactions': 'تراکنش ها',
  'nothing_found': 'چیزی یافت نشد',
  'try_again': 'تلاش دوباره',
  'all': 'همه',
  'backup_seed_words': 'بازیابی عبارت رمز',
  'warning': 'هشدار!',
  'read_agreement_first': 'لطفا توافق نامه را خوانده و با آن موافقت کنید',
  'regenerate': 'تولید دوباره',
  'backed_up': 'بازیابی شد',
  'tokens': 'توکن ها',
  'balance_talan': 'موجودی (طلان)',
  'pending_balance': 'در انتظار : @pending Talan',
  'first_slide_description': 'دریافت TALAN یا توکن های TLRC20 با اسکن یا اشتراک گذاری کیوآرکد اخصاصی یا آدرس خود',
  'second_slide_description': 'ارسال TALAN یا توکن های TLRC20 در چند مرحله کوتاه با اسکن یک کیوآرکد اخصاصی یا چسباندن یک آدرس',
  'control_your_wealth': 'مدیریت دارایی خود',
  'third_slide_description': 'دارایی شما تحت کنترل است و حریم خصوصی شما تحت حفاظت ، '
      ' به ساخت اکانت نیازی ندارید و کلید خصوصی شما در هیچ پایگاه داده ای ذخیره نمی شود',
  'create_new_wallet': 'ساخت کیف پول جدید',
  'restore_wallet': 'بازیابی کیف پول',
  'copy_address': 'رونوشت آدرس',
  'amount': 'مقدار',
  'enter_amount': 'وارد کردن مقدار',
  'restore_wallet_description': 'لطفا عبارات رمز کیف پول خود را به منظور بازیابی آن وارد کنید',
  'confirm': 'تایید',
  'security_center': 'مرکز امنیت',
  'your_address': 'آدرس شما',
  'public_key': 'کلید عمومی',
  'private_key': 'کلید خصوصی',
  'tap_to_reveal': 'برای آشکارسازی لمس کنید',
  'next': 'بعدی',
  'available_balance': 'موجودی',
  'to': 'به',
  'enter_your_address': 'لطفا آدرس را وارد کنید یا',
  'paste': 'چسباندن',
  'address': 'آدرس',
  'settings': 'تنظیمات',
  'language': 'زبان',
  'currency_unit': 'واحد ارز',
  'location': 'مکان',
  'research': 'سرچ مجدد',
  'selectRoom': 'انتخاب اتاق',
  'touch_id': 'اثرانگشت',
  'modify_pi_code': 'تغییر رمز',
  'delete_your_wallet': 'پاک کردن کیف پول',
  'confirm_backup': 'تایید بازیابی',
  'wallet_created': 'کیف پول ساخته شد',
  'secure_your_key': 'لطفا عبارت امنیتی و رمز خود را در جای امنی دخیره کنید.',
  'access_your_wallet': 'دسترسی به کیف پول',
  'previous': 'قبلی',
  'leavingFrom': 'از',
  'goingTo': 'به',
  'traveler_count': 'تعداد مسافرین',
  'flight_class': 'کلاس پرواز',
  'flights_ticket': 'بلیط پروازها',
  'select': 'انتخاب',
  'change': 'تغییر',
  'buy_pay_now': 'خرید و پرداخت آنی',
  'make_payment': 'پرداخت',
  'bookerContactInfo': 'مشخصات رزرو کننده',
  'passengerDetail': 'مشخصات مسافر',
  'bookerContactInfoDesc': 'Booking details and tickets will be send to this email or phone number',
  'enterPassengersDetails': 'جزییات مسافران را وارد کنید',
  'passengerDetailDesc': 'Please enter your first and lastname correctly in English format.',
  'canceling_rules': 'قوانین لغو و جدول قیمت ها',
  'flights_list': 'لیست پروازها',
  'addPassengers': 'افزودن مسافر',
  'confirm_transaction': 'تایید تراکنش',
  'you_are_about_to_send': 'شما در حال ارسال ',
  'space_to': ' به',
  'are_you_sure_to_send': 'آیا از این کار اطمینان دارید؟',
  'delete_wallet': 'پاک کردن کیف پول',
  'delete_wallet_description': 'شما در حال پاک کردن کیف پول طلان خود هستید.'
      ' از ذخیره سازی عبارات رمز خود اطمینان حصال فرمایید'
      ' در غیر این صورت تمام TALAN و توکن های خود را از دست میدهید و قابل بازیابی نیستند'
      ' آیا مطمئن هستید که میخواهید کیف پول خود را پاک کنید؟ ',
  'yes_iam_sure': 'بله مطمئن هستم',
  'cancel': 'لغو',
  'options': 'گزینه ها',
  'pricing': 'بر اساس قیمت',
  "roundtrip": "دو طرفه",
  'byRating': 'بر اساس امتیاز',
  'transaction_sent': 'تراکنش با موفقیت ارسال شد',
  'transaction_sent_description': 'تراکنش با موفقیت ارسال شد . عبارت زیر شناساگر تراکنش شماست',
  'copied_to_clipboard': 'رونوشت برداشته شد',
  'pin_codes_do_not_match': 'رمز ها تطابق ندارند . دوباره سعی کنید',
  'enter_your_current_pin_code': 'رمز حال حاضر خود را وارد کنید',
  'enter_new_pin_code': 'رمز جدید وارد کنید',
  'please_enter_password': 'لطفا رمز را وارد کنید',
  'enter_pin_code_to_unlock_app': 'برای باز شدن برنامه رمز خود را وارد کنید',
  'incorrect_pin_code': 'رمز صحیح نمیباشد\nدوباره سعی کنید',
  'incorrect_pin_code_toast': 'رمز صحیح نمی باشد . دوباره سعی کنید',
  'enter_pin_code': 'لطفا رمز خود را وارد کنید',
  'reenter_for_confirmation': 'برای تایید دوباره وارد کنید',
  'auth_failed': 'احراز هویت موفق نبود',
  'address_copied': 'از آدرس رونشت برداشته شد',
  'your_wallet_deleted': 'کیف پول تان پاک شد',
  'incorrect_order': 'ترتیب کلمات نادرست می باشد',
  'internet_not_connected': 'شما به اینترنت متصل نیستید',
  'agree_to_terms_of_service': 'برای ادامه دادن باید با شرایط استفاده از خدمات موافقت کنید',
  'sync_first': 'ابتدا باید بروزرسانی داده ها انجام شود',
  'last_sync_date_time': 'شما به اینترنت متصل نیستید . آخرین بروزرسانی در تاریخ '
      '@date'
      ' و زمان @time',
  'fill_all_fields': 'شما باید تمام موارد را پر کنید',
  'invalid_seed': 'عبارت رمز نا معتبر',
  'more_balance_needed': 'شما این مقدار موجودی برای ارسال ندارید',
  'invalid_inputs': 'ورودی نا معتبر',
  'something_went_wrong': 'خطایی رخ داد!',
  'yes': 'بله',
  'en': 'English',
  'fa': 'فارسی',
  'wallet': 'کیف پول',
  'services': 'خدمات',
  'dex': 'EXCH',
  'offline_stacking': 'سرمایه گذاری آفلاین',
  'add_delegation': 'اضافه کردن نماینده',
  'super_staker_address': 'آدرس سوپر استیکر',
  'staker_fee': 'فی استیکر',
  'enter_fee': 'فی را وارد کنید',
  'attention': 'توجه',
  'staking_confirmation_message': 'آیا مطمئن هستید که کوین های خود را برای استیکینگ قرار می دهید؟',
  'staking_done_message': 'نمایندگی برای سهام تایید شد. صبر کنید تا 300 بلوک در بلاکچین تأیید شود تا پاداش های سهام را دریافت کنید.',
  'done': 'انجام شد!',
  'staking_block_number': 'شماره بلاک استیک شده',
  'blocks_confirmed_so_far': 'بلاک هایی تاکنون تأیید شده',
  'remove_stake_confirmation_message': 'شما در حال لغو استیک هستین . آیا از این کار اطمینان دارید؟',
  'cancel_staking': 'لغو استیک',
  'amount_balance_required': 'برای انجام این عمل حداقل @amount Talan لازم دارید',
  'nothing_to_show': 'هنوز داده ای برای نمایش وجود ندارد',
  'coming_soon': 'به زودی',
  'staker_address': 'آدرس سوپر استیک کننده',
  'fee': 'فی',
  'about_offline_staking': 'درباره ی استیک آفلاین',
  'offline_staking_description': 'Offline Staking allows holders to choose the operator of the node, while not transferring'
      'their coins to him. Receiving rewards gives users the opportunity to earn profits from staking their coins.'
      'In offline staking , you don\'t need to setup a full node and you even never let your coins to leave your wallet.'
      'Just you show the blockchain that you let the super staker use your address and for this reason you pay fee to super staker node.'
      'The duty of super staker is to be online all the time.'
      'Since Talan’s offline staking does not need an internet connection, it is called offline'
      'staking. In it, instead of tokens, the owners delegate their wallets addresses. The coins'
      'themselves remain in the owner’s wallet and can be used at any given time.The stakers'
      'are separated into two categories, as they are in all Blockchain networks: superstakers'
      'and UTXO representatives, known as Delegators. To participate in offline staking, the'
      'representative’s wallet address is sent to a superstaker.'
      'The superstakers then can act on behalf of the delegators and take a cut of the profits'
      'for doing the staking. However, after the delegation of the wallet,'
      'the owner doesn’t have to be online at all times which means that the owners will receive interest even if they'
      'are not participating directly. The time frames for receiving the rewards is directly'
      'related to the amount of delegated Talans. The more coins you have for staking, the'
      'sooner you will receive the block’s rewards.',
  'canceling_stake_wait_for_blockchain': 'در حال لغو استیک . منتظر تایید بلاک چین بمانید.',
  'seed_phrase': 'عبارت رمز',
  'restore_wallet_with_private_key_description': 'لطفا کلید خصوصی کیف پول خود را به منظور بازیابی آن وارد کنید',
  'invalid_private_key': 'کلید رمز نامعتبر',
  'staked': 'استیک شده',
  'confirmations': 'تاییدیه ها',
  'address_equality': 'آدرس سوپر استیکر نمی تواند با آدرس خودتا یکسان باشد',
  'super_staker_not_verified': 'آدرس ارائه شده به عنوان سوپر استیکر شناخته نشده است',
  'private_key_reveal_warning': 'تحت هیچ شرایطی کلید خصوصی خود را با کسی به اشتراک نگذارید '
      '. در غیر اینصورت ،آن کسی که کلید خصوصی شما را دارد، میتواند به کیف شما دسترسی کامل داشته باشد.',
  'failed_to_create_wallet': 'ساخت کیف پول ناموفق بود',
  'wallet_name': 'نام کیف پول',
  'wallet_name_required': 'شما باید نامی برای کیف پول خود وارد کنید',
  'restore': 'بازیابی',
  'multi_coin_wallet': 'کیف پول چند سکه ای',
  'no_balance_to_send': 'شما موجودی ای برای ارسال ندارید',
  'search_tokens_hint': 'توکن ها را جستجو کنید...',
  'wallets': 'کیف پول ها',
  'wallet_settings': 'تنظیمات @name',
  'edit_wallet_name': 'ویرایش نام کیف پول',
  'export_private_key': 'برون ریزی کلید خصوصی کیف پول',
  'export_wallet_seed_phrase': 'برون ریزی عبارات رمز کیف پول',
  'save': 'ذخیره',
  'empty_wallet_name_message': 'شما باید برای کیف پول یک نام وارد کنید',
  'new_name_saved': 'نام جدید کیف پول ذخیره شد',
  'export_seed_phrase_title': 'عبارت رمز کیف پول @name',
  'export_private_key_title': 'کلید خصوصی کیف پول @name',
  'copy_seed_phrase': 'رونوشت عبارات رمز',
  'copy_private_key': 'رونوشت کلید خصوصی',
  'copied': 'رونوشت گرفته شد',
  'export_seed_phrase_message': 'کیو آر کد بالا حاوی عبارات رمز شماست',
  'export_private_key_message': 'کیو آر کد بالا حاوی کلید خصوصی شماست',
  'exchange': 'اکسچنج',
  'swap': 'سوآپ',
  'you_pay': 'پرداخت شما',
  'you_get': 'دریافت شما',
  'balance': 'موجودی : ',
  'unable_to_add_the_token': 'امکان اضافه کردن این توکن به کیف پول شما وجود ندارد',
  'processing': 'در حال پردازش',
  'finished': 'انجام شد',
  'failed': 'ناموفق',
  'from_address': 'آدرس مبدا :',
  'to_address': 'آدرس مقصد :',
  'pay_in_txid': 'شناساگر دریافت : ',
  'pay_out_txid': 'شناساگر واریز :',
  'date': 'تاریخ',
  'network_fee': 'فی شبکه : ',
  'enter_valid_amount': 'مقدار معتبر وارد کنید',
  'minimum_amount_required': 'حداقل مقدار برای @name @amount می باشد',
  'proceed': 'ادامه',
  'amount_of_coin': 'مقدار @name',
  'exchange_history': 'تاریخچه ی معامله',
  'swap_history': 'تاریخچه ی سوآپ',
  'buy': 'فروش',
  'sell': 'خرید',
  'total': 'مجموع',
  'transfer_done': 'انتقال انجام شد',
  'dex_transfer_message': 'سفارش شما ثبت شد و در حال پردازش است . کد زیر شناسه ی سفارش شماست',
  'only_this_pair': 'فقط @token1 به @token2',
  'all_orders': 'تمام سفارشات',
  'search_token_you_pay': 'توکنی که میخواهید پرداخت کنید را جستجو کنید',
  'search_token_you_get': 'توکنی که میخواهید دریافت کنید را جستجو کنید',
  'not_enough_token': 'موجودی @token شما برای انجام معامله کافی نیست',
  'request_canceled': 'درخواست لغو شد',
  'maintenance_message': 'متاسفانه در حال حاضر اپ در دسترس نمی باشد لطفا لحظاتی دیگر برای ورود به اپ اقدام کنید',
  'unexpected_problem_try_later': 'اتفاقی غیرمنتظره رخ داد، لطفاً بعداً دوباره امتحان کنید',
  'exchanging': 'در حال مبادله',
  'sending': 'در حال ارسال',
  'refunded': 'برگردانده شده',
  'hold': 'متوقف شده',
  'expired': 'منقضی شده',
  'total_value': 'مجموع دارایی',
  'pay_in_confirmations': 'تاییدیه های واریز : ',
  'pay_out_confirmations': 'تاییدیه های برداشت : ',
  'memo': 'ممو',
  'tag': 'تگ',
  'enter_memo': 'ممو را وارد کنید (اختیاری)',
  'enter_tag': 'تگ را وارد کنید (اختیاری)',
  'swap_unavailable': 'در حال حاضر سوآپ در دسترس نمی باشد',
  'exchange_unavailable': 'در حال حاضر معامله در دسترس نمی باشد',
  'collections': 'کلکسیون',
  'create_nft': 'ساخت ان اف تی',
  'nft_name': 'نام ان اف تی',
  'nft_desc': 'توضیحات ان اف تی',
  'nft_amount': 'مقدار ان اف تی',
  'enter_name': 'نام را وارد کنید',
  'enter_desc': 'توضحیات را بنویسید',
  'nft_image_required': 'عکس ان اف تی اجباری است',
  'nft_name_required': 'نام ان اف تی اجباری است',
  'nft_amount_required': 'مقدار ان اف تی اجباری است',
  'nft_amount_could_not_be_zero': 'مقدار ان اف تی نمی تواند صفر باشد',
  'nft_amount_exceeded': 'مقدار ان اف تی از حد مجاز بیشتر است',
  'nft_desc_required': 'توضیحات ان اف تی اجباری است',
  'nft_created_message': 'ان اف تی با موفقیت ساخته شد . کد زیر شناساگر تراکنش شماست',
  'nft_created_title': 'ان اف تی ساخته شد',
  'unable_to_load': 'بارگذاری ناموفق',
  'transaction_id': 'شناساگر تراکنش',
  'description': 'توضیحات',
  'available_amount': 'مقدار قابل دسترس',
  'your_balance': 'موجودی شما',
  'date_created': 'تاریخ ساخت',
  'send_nft': 'ارسال ان اف تی',
  'address_required': 'آدرس اجباری است',
  'ipfs': 'IPFS',
  'create_nft_confirmation_message': 'آیا از ساخت این ان اف تی اطمینان دارید؟',
  'nft_author': 'سازنده(اختیاری)',
  'nft_author_hint': 'نام سازنده را وارد کنید(اختیاری)'
};
const Map<String, String> persianApp = {
  "login": "ورود",
  "enterPhone": "شماره موبایل خود را وارد کنید",
  "confirmAndContinue": "ثبت و ادامه",
  "enterVerifyCode": "کد تایید را وارد کنید",
  "resendCode": "ارسال دوباره",
  "editPhone": "ویرایش موبایل",
  "callSupport": "تماس با پشتیبانی",
  "setPassword": "ایجاد رمز عبور",
  "createNewPassword": "ایجاد رمز عبور جدید",
  "passWordShouldBe4": "کد باید 4 رقم باشد",
  "completeInformation": "تکمیل اطلاعات",
  "firstName": "نام",
  "lastName": "نام خانوادگی",
  "birthday": "تاریخ تولد",
  "day": "روز",
  "month": "ماه",
  "year": "سال",
  "province": "استان",
  "gender": "جنسیت",
  "male": "مرد",
  "female": "زن",
  "iDNumber": "iDNumber",
  "search_flights": "جستجو پرواز",
  "fillLater": "بعدا پر میکنم",
  "coin": "سکه",
  "increaseBalance": "افزایش موجودی",
  "ourServices": "خدمات ما",
  "chargePhone": "شارژ موبایل",
  "internet": "اینترنت",
  "walletToWallet": "کیف به کیف",
  "payBills": "پرداخت قبض",
  "innerHotel": "هتل داخلی",
  "foreignHotel": "هتل خارجی",
  "foreignHotelsList": " لیست هتل های خارجی",
  "innerFlights": "پرواز داخلی",
  "foreignFlights": "پرواز خارجی",
  "comingSoon": "به زودی",
  "home": "خانه",
  "barcode": "بارکد",
  "coinBag": "کیف سکه",
  "searchForeignHotel": "جستجوی هتل خارجی",
  "addRoom": "اضافه کردن اتاق",
  "search": "جستجو",
  "searchSummary": "خلاصه جستجو",
  "searchAgain": "جستجو مجدد",
  "searchWithHotelName": "جستجو بر اساس نام هتل",
  "showOnMap": "نمایش روی نقشه",
  "sort": "نمایش مرتب سازی",
  "highestPrice": "بیشترین قیمت",
  "hotelName": "نام هتل",
  "chooseRoom": "انتخاب اتاق",
  "filtering": "فیلترینگ",
  "startPrice": "شروع قیمت",
  "submit": "ثبت",
  "removeFilters": "پاک کردن فیلترها",
  "sortAndFiltering": "مرتب سازی و فیلتر کردن",
  "accordingToGrade": "بر اساس رتبه",
  "facilities": "امکانات",
  "meal": "وعده غذایی",
  "priceRange": "بازه قیمتی",
  "region": "منطقه",
  "clearFilters": "پاک کردن فیلتر",
  "hotelPage": "صفحه هتل",
  "hotelInformation": "اطلاعات هتل",
  "hotelContact": "اطلاعات تماس هتل",
  "hotelFacilities": "امکانات هتل",
  "roomFacilities": "امکانات اتاق",
  "hotelDetail": "جزئیات هتل",
  "directCall": "تماس مستقیم",
  "more": "بیشتر",
  "reserveRoom": "رزرو اتاق",
  "passengersInformation": "اطلاعات مسافران",
  "passengersInfoInput": "اطلاعات مسافران رو وارد کنید",
  "pay": "پرداخت",
  "reservatoreCallInfo": "اطلاعاات رزرو کننده",
  "email": "آدرس پست الکترونیکی",
  "optional": "- اختیاری -",
  "phoneNumber": "شماره موبایل",
  "passengersDetail": "جزئیات مسافران",
  "nationality": "ملیت",
  "addPassenger": "اضافه کردن مسافر",
  "removePassenger": "حذف مسافر",
  "putDescriptionHere": "توضیحات را اینجا وارد کنید",
  "considerations": "ملاحظات",
  "searchIranianFlight": "جستجو پرواز داخلی",
  "beginning": "مبدا",
  "destination": "مقصد",
  "dateOfDeparture": "تاریخ پرواز",
  "count": "تعداد",
  "classs": "کلاس",
  "innerFlightList": "لیست پرواز داخلی",
  "choose": "انتخات",
  "remaining": "مانده",
  "person": "نفر",
  "lowestPrice": "کمترین قیمت",
  "highestDiscount": "بیشترین تخفیف",
  "moreDetail": "اطلاعات بیشتر",
  "innerFlightTicket": "بلیط پرواز داخلی",
  "flightLength": "طول پرواز",
  "priceDetail": "جزئیات قیمت",
  "adult": "بزرگسال",
  "child": "کودک",
  "baby": "نوزاد",
  "refundRule": "قوانین استرداد",
  "understand": "فهمیدم",
  "iranian": "ایرانی",
  "foreign": "خارجی",
  "englishName": "نام به انگلیسی",
  "englishLastName": "نام خانوادگی به انگلیسی",
  "example": "مثال",
  "enterYourNameCorrectly": "نام خود را به درستی وارد کنید",
  "andSameAsPassport": "مشابه پاسپورت",
  "georgian": "میلادی",
  "countryOfBirth": "محل تولد",
  "countryOfIssue": "محل ثبت",
  "passportExpirationDate": "تاریخ انقضاء پاسپورد",
  "oneWayFlight": "پرواز یکطرفه",
  "twoWayFlight": "پرواز دوطرفه",
  "returningDate": "تاریخ بازگشت",
  "edit": "ویرایش",
  "stop": "توقف",
  "flightRulesAndCancelation": "قوانین پرواز و کنسلی",
  "basicPrice": "قیمت پایه",
  "tax": "مالیات",
  "totalPrice": "قیمت کل",
  "reserve": "رزرو",
  "flightNumber": "شماره پرواز",
  "allowedCargo": "بار مجاز",
  "passportNumber": "شماره پاسپورت",
  "myPhoneNumber": "شماره موبایل من",
  "enterPhoneNumber": "شماره موبایل را وارد کنید",
  "fromContacts": "از مخاطب ها",
  "operatorWillBeRecognized": "اپراتور تشخیص داده میشود",
  "buyCharge": "خرید شارژ",
  "chooseSimCart": "انتخاب سیمکارت",
  "credit": "اعتباری",
  "permanent": "دائمی",
  "rial": "ریال",
  "chosenPrice": "قیمت انتخاب شده",
  "from": "از",
  "chooseIntendedCharge": "شارژ مورد نظر را انتخاب کنید",
  "equal": "برابر",
  "walletBagBalance": "موجودی کیف پول",
  "insufficientBalance": "موجودی نا کافی",
  "watterBill": "قبض آب",
  "powerBill": "قبض برق",
  "gasBill": "قبض گاز",
  "phoneBill": "قبض تلفن",
  "mobileBill": "قبض موبایل",
  "violation": "خلافی",
  "otherBills": "بقیه قبض ها",
  "readGuid": "راهنما",
  "view": "مشاهده",
  "paperBill": "قبض کاغذی",
  "id": "شناسه",
  "billsHistory": "تاریخچه قبوض",
  "billInquiry": "استعلام قبض",
  "barcodeScan": "اسکن بارکد",
  "bill": "قبض",
  "price": "قیمت",
  "cityCode": "کد شهر",
  "staticPhoneNumber": "شماره تلفن ثابت",
  "staticPhone": "تلفن ثابت",
  "chooseOperator": "انتخاب اپراتور",
  "guid": "راهنما",
  "inCaseOfTransfer": "در صورت انتقال",
  "watter": "آب",
  "power": "برق",
  "gas": "گاز",
  "mobile": "موبایل",
  "chooseTimeRange": "انتخاب بازه زمانی",
  "paymentId": "شناسه پرداخت",
  "billId": "شناسه قبض",
  "toman": "تومان",
  "lastPayments": "آخرین پرداخت ها",
  "billType": "نوع قبض",
  "trackingNumber": "شماره پیگیری",
  "successFull": "موفق",
  "paymentSuccessful": "پرداخت موفق",
  "hourly": "ساعتی",
  "daily": "روزانه",
  "weekly": "هفتگی",
  "monthly": "ماهانه",
  "threeWeeks": "سه ماهه",
  "sixWeeks": "شش ماهه",
  "yearly": "سالیانه",
  "gig": "گیگابایت",
  "internetPackage": "بسته اینترنت",
  "nextLevel": "مرحله بعد",
  "myProfile": "پروفایل من",
  "changePassword": "تغییر رمز عبور",
  "qAnda": "پرسش و پاسخ",
  "support": "پشتیبانی",
  "rulesAndConditions": "قوانین و مقررات",
  "shareWithFriends": "اشتراک گذاری با دوستان",
  "aboutUs": "درباره ما",
  "exitApp": "خروج از برنامه",
  "ourSocialMedias": "شبکه های اجتماعی ما",
  "copy": "کپی",
  "yourBalance": "موجودی شما",
  "sendNewTicket": "ارسال تیکت جدید",
  "ticketTitle": "عنوان تیکت",
  "ticketText": "متن تیکت",
  "writeHere": "اینجا بنویسید",
  "writeYourProblemHere": "مشکل خود را اینجا بنویسید",
  "addAttachment": "اضافه کردن الحاقیات",
  "chooseFile": "انتخاب فایل",
  "addToDraft": "افزودن به چکنویس",
  "chooseFlight": "انتخاب پرواز",
  "nationalCode": "کد ملی",
  "billServices": "خدمات پرداخت قبوض",
  "enterBillIdAndPayId": "لطفا شناسه قبض و شناسه پرداخت را وارد کنید",
  "chooseInternetPackage": "انتخات بسته اینترنت",
  "pleaseChooseInternetPackage": "لطفا بسته اینترنتی خود را انتخاب کنید",
  "ticketList": "لیست تیکت ها",
  "youCanSeeListTicket": "در اینجا لیستی از تیکت ها را میبینید",
};
